import Faq from './Faq';
import { useState } from 'react';
import CalculationModal from './CalculationModal';
import Selection from './Selection';

const Faqs = [
  {
    title: 'What is SIP?',
    description:
      'Systematic Investment Plan or SIP is the most disciplined style of investment in which a fixed amount of money is invested at regular intervals (yearly, quarterly, monthly). For SIP you will have to decide the investment amount, the SIP date and the scheme in which you want to invest.',
  },
  {
    title: 'What are the benefits of SIP?',
    description:
      'In SIP you invest money without speculating the market condition i.e. one invests without timing the market. So, in SIP the investments are done over different market cycles and therefore you benefit from rupee-cost averaging factor. <br/> With SIP one can stay invested for a longer period of time thus, your money stays invested and generates return over a long term. So, your investment gets sufficient time to enjoy the power of compounding. <br/> One can start a SIP with very small investment say Rs 500 per month. This means that you need not commit huge amount of money that is difficult to pay in future.',
  },
  {
    title: 'How does our SIP calculator work?',
    description:
      'SIP Calculator or the SIP Investment Calculator uses some variables as inputs. It then processes these inputs to give you the total future value of investments and total earnings generated by your investment. <br/> Inputs to be given in SIP Calculator: <br/> Investment Type: Select whether you choose to make SIP on monthly basis or yearly basis. <br/> Investment amount: In this column put the SIP amount you wish to invest regularly. <br/> Expected Rate of Return: Here, you need to put the rate that he/she is expecting for the investments made during the entire period. In this SIP calculator you need to put rate of return on per annum basis. Rate can be selected on the basis of the fund’s past track record. <br/> Tenure: In this column one should enter the time period (in years) for which he/she is willing to make the investment.',
  },
  {
    title: 'Can I miss the payment of SIP?',
    description:
      'Yes, one can miss the payment of SIP if the fund that you have chosen provides the facility to pause the payment.',
  },
  {
    title: 'What to choose - SIP or Lumpsum?',
    description: `Ideally you should invest (whether in SIP or Lumpsum) based on your investment profile which includes current income, expenditure, age, risk profile and financial goals.
    <br/>
      The major benefit of SIP over lumpsum investment is that one need not time the market as you invest systematically through both the ups and downs of the market so the returns that you generate is weighted average return. With SIP, your money is spread over time, and only some parts of your total investments face the risk of market volatility.
      <br/>
      In lumpsum one has to time the market to generate higher returns. This means that if one is sure that there won’t be any major correction in the market just after your investment date then lumpsum investment (one-time investment) is preferable.`,
  },
  {
    title: 'Do SIPs offer Tax Benefits?',
    description:
      'The SIP investment done through ELSS (Equity Linked Savings Scheme) offers maximum tax benefits up to 1.5 lakh rupees per year under section 80C.',
  },
  {
    title: 'Can SIP be started online?',
    description:
      'Yes, one can start SIP online after selecting the right funds in which you want to invest. The funds can be selected based on your investment objectives and risk profile.',
  },
];

const SipCalculator = () => {
  const [open, setOpen] = useState(false);
  const [values, setValues] = useState({
    investment: 0,
    rate_of_return: 0,
    period_of_investment: 0,
    total_future_return: 0,
    investment_frequency: 'Monthly',
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    const {
      investment,
      rate_of_return,
      period_of_investment,
      investment_frequency,
    } = values;

    const final_rate =
      investment_frequency === 'Monthly'
        ? rate_of_return / (12 * 100)
        : rate_of_return / 100;

    const final_period =
      investment_frequency === 'Monthly'
        ? period_of_investment * 12
        : period_of_investment;

    const ans =
      investment *
      (((Math.pow(1 + final_rate, final_period) - 1) / final_rate) *
        (1 + final_rate));

    setValues((preValues) => ({
      ...preValues,
      total_future_return: ans.toFixed(2),
    }));
    setOpen((pre) => !pre);
  };

  return (
    <>
      {open && (
        <CalculationModal values={values} open={open} setOpen={setOpen} />
      )}
      <div className="bg-white rounded-lg shadow sm:max-w-md sm:w-full sm:mx-auto sm:overflow-hidden">
        <div className="px-4 py-8 sm:px-10">
          <div className="relative mt-6">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-gray-300"></div>
            </div>
            <div className="relative flex justify-center text-xl leading-5">
              <span className="px-2 text-gray-800 bg-white">
                SIP Calculator
              </span>
            </div>
          </div>
          <form onSubmit={handleSubmit}>
            <div className="mt-6">
              <div className="w-full space-y-6">
                <div className="w-full">
                  <div className="relative">
                    <label className="text-lg font-medium text-gray-700">
                      Frequency of Investment
                    </label>
                    <Selection values={values} setValues={setValues} />
                  </div>
                </div>
                <div className="w-full">
                  <div className="relative">
                    <label className="text-lg font-medium text-gray-700">
                      {values.investment_frequency} Investment Amount
                      <span className="text-red-500">*</span>
                      <input
                        type="number"
                        id="search-form-price"
                        className="flex-1 w-full px-4 py-2 text-base text-gray-700 placeholder-gray-400 bg-white border border-transparent border-gray-300 rounded-lg shadow-sm appearance-none  focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-transparent"
                        placeholder="Ex: 10000"
                        onChange={(e) =>
                          setValues((preValues) => ({
                            ...preValues,
                            investment: e.target.value,
                          }))
                        }
                        min="100"
                        required
                      />
                    </label>
                  </div>
                </div>
                <div className="w-full">
                  <div className="relative ">
                    <label className="text-lg font-medium text-gray-700">
                      Expected rate of return (P.A.)
                      <span className="text-red-500">*</span>
                      <input
                        type="number"
                        id="search-form-location"
                        className="flex-1 w-full px-4 py-2 text-base text-gray-700 placeholder-gray-400 bg-white border border-transparent border-gray-300 rounded-lg shadow-sm appearance-none focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-transparent"
                        placeholder="Ex: 12%"
                        required
                        min="1"
                        max="50"
                        onChange={(e) =>
                          setValues((preValues) => ({
                            ...preValues,
                            rate_of_return: e.target.value,
                          }))
                        }
                      />
                    </label>
                  </div>
                </div>
                <div className="w-full">
                  <div className="relative ">
                    <label className="text-lg font-medium text-gray-700">
                      Tenure (in years) (Up to 50 Years)
                      <span className="text-red-500">*</span>
                      <input
                        type="number"
                        id="search-form-name"
                        className="flex-1 w-full px-4 py-2 text-base text-gray-700 placeholder-gray-400 bg-white border border-transparent border-gray-300 rounded-lg shadow-sm appearance-none  focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-transparent"
                        placeholder="Ex:10"
                        required
                        min="1"
                        max="50"
                        onChange={(e) =>
                          setValues((preValues) => ({
                            ...preValues,
                            period_of_investment: e.target.value,
                          }))
                        }
                      />
                    </label>
                  </div>
                </div>
                <div>
                  <span className="block w-full rounded-md shadow-sm">
                    <button
                      type="submit"
                      className="w-full px-4 py-2 text-base font-semibold text-center text-white transition duration-200 ease-in bg-yellow-500 rounded-lg shadow-md hover:bg-yellow-600 focus:ring-yellow-500 focus:ring-offset-yellow-200 focus:outline-none focus:ring-2 focus:ring-offset-2 "
                    >
                      Plan My Future Value
                    </button>
                  </span>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div className="px-4 py-6 border-t-2 border-gray-200 bg-gray-50 sm:px-10">
          <p className="text-xs leading-5 text-gray-500">
            Thinking of making a Lumpsum investment? Calculate the future value
            of your wealth using our Lumpsum Calculator.
          </p>
        </div>
      </div>
      <Faq heading="SIP" Faqs={Faqs} />
    </>
  );
};

export default SipCalculator;
